version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: excusas-c3:latest
    container_name: excusas_web
    depends_on:
      - db
    ports:
      - "8090:80"  # Jenkins usa 8080
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: v_exc_asig_mat_est
      DB_USERNAME: root
      DB_PASSWORD: root_pass
    volumes:
      - .:/var/www/html
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: excusas_db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: v_exc_asig_mat_est
      MYSQL_USER: root
      MYSQL_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
      # Se importa autom√°ticamente al crear el contenedor
      - ./v_exc_asig_mat_est.sql:/docker-entrypoint-initdb.d/v_exc_asig_mat_est.sql:ro
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: excusas_phpmyadmin
    depends_on:
      - db
    ports:
      - "8091:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_pass
      UPLOAD_LIMIT: 100M
    restart: unless-stopped

volumes:
  db_data:
